CREATE TABLE Users (
    UserId BIGSERIAL PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- DROP TABLE Users CASCADE;
